//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bansach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int Iduser { get; set; }
        public int Idsach { get; set; }
        public string Noidung { get; set; }
        public Nullable<System.DateTime> Thoigian { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual USER USER { get; set; }
    }
}
