//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bansach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONBANLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONBANLE()
        {
            this.CHITIETHDBLs = new HashSet<CHITIETHDBL>();
        }
    
        public int Idhdbl { get; set; }
        public Nullable<int> Idnhanvien { get; set; }
        public Nullable<int> Iduser { get; set; }
        public Nullable<System.DateTime> Ngaydat { get; set; }
        public Nullable<System.DateTime> Ngaygiao { get; set; }
        public string Hotennguoinhan { get; set; }
        public string Diachinhan { get; set; }
        public string SDTnguoinhan { get; set; }
        public string Trangthai { get; set; }
        public string Tongtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDBL> CHITIETHDBLs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual USER USER { get; set; }
    }
}
