//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bansach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LIENHE
    {
        public int Idlienhe { get; set; }
        [StringLength(50, ErrorMessage = "Độ dài tối đa của họ là 50 ký tự")]
        public string Ho { get; set; }
        [StringLength(10, MinimumLength = 2, ErrorMessage = "Độ dài tối thiểu của tên là 2 ký tự, tối đa 10 ký tự")]
        [Required(ErrorMessage = "Tên không được để trống")]
        public string Ten { get; set; }
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Độ dài tối thiểu của email là 5 ký tự, tối đa 100 ký tự")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Email phải đúng định dạng X@X.X")]
        [Required(ErrorMessage = "Email không được để trống")]
        public string Email { get; set; }
        [RegularExpression(@"^((09(\d){8})|(086(\d){7})|(088(\d){7})|(089(\d){7})|(01(\d){9}))$")]
        [Required(ErrorMessage = "Số điện thoại không được để trống")]
        public string SDT { get; set; }
        public string Noidung { get; set; }
    }
}
