//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bansach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
            this.CHITIETHDBLs = new HashSet<CHITIETHDBL>();
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.TACGIAs = new HashSet<TACGIA>();
        }
    
        public int Idsach { get; set; }
        public Nullable<int> IdNXB { get; set; }
        public Nullable<int> Iddanhmuc { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string Tuasach { get; set; }
        public string Gioithieusach { get; set; }
        public Nullable<int> Khoiluong { get; set; }
        public Nullable<System.DateTime> Ngayphathanh { get; set; }
        public string Ngonngu { get; set; }
        public string Nguoidich { get; set; }
        public string Kichthuoc { get; set; }
        public Nullable<int> Sotrang { get; set; }
        public string Giagoc { get; set; }
        public string Giamgia { get; set; }
        public string Giaban { get; set; }
        public string Motangan { get; set; }
        public string Hinhanh { get; set; }
        public string Masach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDBL> CHITIETHDBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACGIA> TACGIAs { get; set; }
    }
}
