//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bansach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int Idtintuc { get; set; }
        public string Tieude { get; set; }
        public Nullable<System.DateTime> Thoigiandang { get; set; }
        public string Noidungtomtat { get; set; }
        public string Hinhanh { get; set; }
        public string Vietboi { get; set; }
        public string Soluotxem { get; set; }
        public string Tieudengan { get; set; }
    }
}
