//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bansach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.HOADONBANLEs = new HashSet<HOADONBANLE>();
        }

        public int Iduser { get; set; }
        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        [StringLength(30, ErrorMessage = "Độ dài tối thiểu của mật khẩu là 8 ký tự, tối đa 30 ký tự")]
        [RegularExpression(@"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$", ErrorMessage = "Mật khẩu phải đúng định dạng Xx123")]
        public string Matkhau { get; set; }
        [Required(ErrorMessage = "Email không được để trống")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Độ dài tối thiểu của email là 5 ký tự, tối đa 100 ký tự")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Email phải đúng định dạng X@X.X")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Họ tên không được để trống")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Độ dài tối thiểu của Họ tên là 3 ký tự, tối đa 50 ký tự")]
        public string Hoten { get; set; }
        public string Gioitinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        [Required(ErrorMessage = "Tên tài khoản không được để trống")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Độ dài tối thiểu của tài khoản là 3 ký tự, tối đa 50 ký tự")]
        public string Taikhoan { get; set; }
        [StringLength(200, MinimumLength = 5, ErrorMessage = "Độ dài tối thiểu của địa chỉ là 5 ký tự, tối đa 200 ký tự")]
        public string Diachi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBANLE> HOADONBANLEs { get; set; }
    }
}
